### ISSUE TITLE
Can't connect over wifi

### ISSUE THREAD

**Issue by Bexanderthebex** [raareyes/CMSC137_Rawr#6]
Not sure kung kailangan nito pero triny namin over wifi and may error

ERROR:
Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: 2
	at Server.run(Server.java:151)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Bexanderthebex** [comment]
Might be network dependent kasi yung mga kaibigan ko triny mag-laro ng dota at mag-connect over UPLB at hindi sila magkakitaan

**Comment by raareyes** [comment]
baka kasi mag kaiba yung subnet nung mga client..
